// Test definitions. Do NOT edit this file!
#define CATCH_CONFIG_MAIN // defines main() automatically
#include <iostream>
#include "catch.hpp"
#include "Q91.hpp"
// tests for exercise 1

TEST_CASE("Ex1 makeEmpRecord() ", "[example]")
{
	int numEmp, cnt;
	Employee emp[SIZE];
	string dname;

	numEmp = makeEmpRecord(emp);
	cout << "There are " << numEmp << " employees in the structure array. \n\n";
	INFO("The number of Employess shoud be 10");
	REQUIRE(numEmp == 10);
	INFO("Print the last Employee");
	printEmp(emp, numEmp, 9);

	dname = "HR";
	cnt = findEmp(emp, numEmp, dname);
	cout << "Total Employess found : " << cnt << endl;
	INFO("The number of Employess in " << dname << " 2");
	REQUIRE(cnt == 2);

	dname = "Computer";
	cnt = findEmp(emp, numEmp, dname);
	cout << "Total Employess found : " << cnt << endl;
	INFO("The number of Employess in " << dname << " 4");
	REQUIRE(cnt == 4);
}